name: "HyperHDR"
description: "HyperHDR Ambilight for Home Assistant"
version: "21.0.0.0"
slug: "hyperhdr"
startup: services
boot: auto
image: "obaida/hyperhdr-arm64:latest"
webui: "http://[HOST]:[PORT:8090]"
ingress: false
panel_icon: "mdi:television-ambient-light"
arch:
  - aarch64
ports:
  8090/tcp: 8090
  19444/tcp: 19444
map:
  - config:rw
init: false
