name: Build & Push HyperHDR

on:
  workflow_dispatch:
  schedule:
    - cron: "0 2 * * *"  # Tous les jours à 2h du matin

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout HyperHDR source
        uses: actions/checkout@v4
        with:
          repository: awawa-dev/HyperHDR
          ref: master
          submodules: true

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/arm64
          push: true
          tags: obaida/hyperhdr-arm64:latest
